apiVersion: v1
kind: Service
metadata:
  name: nginx-demo2
spec:
  type: ClusterIP
  selector:
    app: nginx-demo2
  ports:
    - name: http
      port: 9891
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
