apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  rules:
  - host: teste-argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8088
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: argocd
type: Opaque
data:
  username: dXNlcg==  # "user" em base64
  password: cGFzc3dvcmQ=  # "password" em base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: argocd
data:
  index.html: |
    <html>
    <head><title>Teste ArgoCD</title></head>
    <body>
      <h1>Teste GitOps</h1>
      <p>Teste do FluxCD com Nginx, para apresentacao</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8088
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
      volumes:
      - name: config-volume
        configMap:
          name: my-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argocd
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
